#ifndef DATA_RELATIONSHIP_H_
#define DATA_RELATIONSHIP_H_

enum HOTEL_MST
{
	HOTEL_ID = 0,
	HOTEL_NAME,
	ADDRESS,
	TEL,
};

enum ROOM_STATUS_MST
{
	ROOM_STATUS_MST_ROOM_STATUS_ID = 0,
	ROOM_STATUS_MST_HOTEL_ID,
	ROOM_STATUS_MST_ROOM_ID,
	ROOM_STATUS_MST_ROOM_TYPE_ID,
	ROOM_STATUS_MST_CUSTOMER_NAME,
	ROOM_STATUS_MST_ROOM_STATUS,
};

enum DISCOUNT_MST
{
	DISCOUNT_MST_ID = 0,
	DISCOUNT_MST_HOTEL_ID,
	DISCOUNT_MST_ROOM_TYPE_ID,
	DISCOUNT_MST_DISCOUNT,
};
#endif DATA_RELATIONSHIP_H_