#ifndef DATA_RELATIONSHIP_H_
#define DATA_RELATIONSHIP_H_

enum HOTEL_MST
{
	HOTEL_MST_HOTEL_ID = 0,
	HOTEL_MST_HOTEL_NAME,
	HOTEL_MST_ADDRESS,
	HOTEL_MST_TEL,
};

enum ROOM_STATUS_MST
{
	ROOM_STATUS_MST_ROOM_STATUS_ID = 0,
	ROOM_STATUS_MST_HOTEL_ID,
	ROOM_STATUS_MST_ROOM_ID,
	ROOM_STATUS_MST_ROOM_TYPE_ID,
	ROOM_STATUS_MST_CUSTOMER_NAME,
	ROOM_STATUS_MST_ROOM_STATUS,
	ROOM_STATUS_MST_FEE,
};

enum DISCOUNT_MST
{
	DISCOUNT_MST_ID = 0,
	DISCOUNT_MST_HOTEL_ID,
	DISCOUNT_MST_ROOM_TYPE_ID,
	DISCOUNT_MST_DISCOUNT,
};

enum ROOM_MST
{
	ROOM_MST_ID,
	ROOM_MST_TYPE,
	ROOM_MST_PRICE,
	ROOM_MST_PRICE_UNIT,
};

#endif DATA_RELATIONSHIP_H_